---
#SkyWars config file, @LINK: https://github.com/svilex/SkyWars-PocketMine
CONFIG_VERSION: 0.500000

##########_GAME_#############
banned.commands.while.in.game:
- /hub
- /lobby
- /spawn
- /tpa
- /tp
- /tpaccept
- /back
- /home
- /f
starvation.can.damage.inArena.players: false
drops.in.arena: false
start.when.full: true
needed.players.to.run.countdown: 1
chest.refill: true
chest.refill.rate: 240
reward.winning.players: false
reward.value: 100

##########_JOIN-SIGN_#############
sign.knockBack: true
knockBack.radius.from.sign: 1
knockBack.intensity: 2
knockBack.follow.sign.direction: false

##########_RESPAWN_#############
always.spawn.in.defaultLevel: true
clear.inventory.on.respawn&join: false
clear.inventory.on.arena.join: true
clear.effects.on.respawn&join: false
clear.effects.on.arena.join: true

##########_WORLD_#############
world.generator.air: true
world.reset.from.zip: true
...
